/**
 * Generated by scripts/gen_types.py from the backend Pydantic models.
 * Do not edit by hand: run `python scripts/gen_types.py` after changing
 * backend/app/domain/models.py. `pytest backend/tests/test_contract.py`
 * fails when this file is out of date.
 */


export interface Alert {
  alert_id: string;
  kind: AlertKind;
  step_id?: string | null;
  rule_id?: string | null;
  message: string;
  opened_at: number;
  opened_evidence?: EvidenceRef | null;
  resolved?: boolean;
  resolved_at?: number | null;
  resolved_evidence?: EvidenceRef | null;
  /** False when the alert rests on missing rather than absence evidence, which cannot support a failure verdict. */
  supported?: boolean;
}


export type AlertKind = "wrong_order" | "missing_required" | "prereq_unconfirmed" | "insufficient_evidence";


export interface Attempt {
  attempt_id: string;
  skill_id: string;
  media_id?: string | null;
  live_session_id?: string | null;
  created_at?: string;
  status?: AttemptStatus;
  mode?: "upload" | "live";
  config?: EngineConfig;
  observations?: Observation[];
  events?: EngineEvent[];
  step_states?: Record<string, StepState>;
  alerts?: Alert[];
  verdict?: Verdict;
  reasons?: string[];
  limitations?: string[];
  provenance?: Provenance;
  error?: string | null;
}


export interface AttemptDetail {
  attempt: Attempt;
  skill: SkillGraph;
}


export interface AttemptRequest {
  video_id: string;
  mode?: string;
}


export type AttemptStatus = "running" | "complete" | "failed";


/** Explicit engine configuration. Part of the replay key. */
export interface EngineConfig {
  min_confidence?: number;
  confirmations_required?: number;
  live_confirmations_required?: number;
  /** Two observations of one step count as independent confirmations only if their source windows start at least this far apart, so overlapping windows cannot confirm the same event twice. */
  independent_gap_s?: number;
  mode?: "upload" | "live";
}


export interface EngineEvent {
  seq: number;
  type: EngineEventType;
  step_id?: string | null;
  rule_id?: string | null;
  alert_id?: string | null;
  /** Source time of the triggering observation */
  t: number;
  message: string;
  observation_id?: string | null;
  evidence?: EvidenceRef | null;
}


export type EngineEventType = "step_started" | "step_done" | "step_reverted" | "step_skipped" | "order_violation" | "prereq_unconfirmed" | "low_confidence_ignored" | "uncertain_observation" | "absence_recorded" | "duplicate_ignored" | "confirmation_pending" | "alert_resolved" | "missing_required" | "verdict";


export interface EngineResult {
  step_states?: Record<string, StepState>;
  events?: EngineEvent[];
  alerts?: Alert[];
  verdict?: Verdict;
  reasons?: string[];
}


export interface ErrorBody {
  code: string;
  message: string;
}


export interface ErrorResponse {
  error: ErrorBody;
}


/** A pointer a human can click to inspect what the system saw. */
export interface EvidenceRef {
  video_id: string;
  t_start: number;
  t_end: number;
  frame_path?: string | null;
  note?: string | null;
}


/** A sampled frame kept with its true source timestamp. */
export interface Frame {
  /** Sample index within the video */
  index: number;
  /** Source video timestamp in seconds */
  timestamp_s: number;
  /** Path relative to the media root */
  media_path: string;
  sha256: string;
}


export interface HealthResponse {
  status: "ok";
  version: string;
  provider: ProviderHealth;
  media_root: string;
  frontend_built: boolean;
}


export interface JobAccepted {
  job_id: string;
  events_url: string;
}


export interface Observation {
  observation_id: string;
  window_id: string;
  step_id: string;
  status: ObservationStatus;
  confidence: number;
  t_start: number;
  t_end: number;
  evidence: EvidenceRef;
  rationale?: string;
  provenance?: Provenance;
}


export type ObservationStatus = "completed" | "in_progress" | "undone" | "absent" | "uncertain";


/** The before step must happen before the after step, with a stated reason. */
export interface OrderingRule {
  rule_id: string;
  kind?: RuleKind;
  before: string;
  after: string;
  reason: string;
  proposed_by_model?: boolean;
  confirmed_by_expert?: boolean;
}


/** Where an observation or description actually came from. */
export type Provenance = "LIVE" | "CACHED" | "MOCK";


export interface ProviderHealth {
  provider: string;
  model?: string | null;
  configured: boolean;
  cache_mode: string;
  provenance_label: Provenance;
  detail?: string;
}


export interface PublishResponse {
  skill: SkillGraph | null;
  validation: ValidationResult;
}


export interface ReplayResponse {
  attempt_id: string;
  identical: boolean;
  verdict: Verdict;
  previous_verdict: Verdict;
  event_count: number;
  previous_event_count: number;
  differences: string[];
}


/** Who approved what. Publication requires expert review. */
export interface ReviewInfo {
  reviewed?: boolean;
  reviewed_at?: string | null;
  edited_steps?: string[];
  confirmed_rules?: string[];
  reviewer_note?: string;
}


export type RuleKind = "order" | "safety";


export interface SkillGraph {
  skill_id: string;
  title: string;
  summary?: string;
  source_video_id?: string | null;
  created_at?: string;
  updated_at?: string;
  status?: SkillStatus;
  objects?: string[];
  steps?: Step[];
  rules?: OrderingRule[];
  review?: ReviewInfo;
  provenance?: Provenance;
  /** Problems found in model output that a human must resolve. */
  validation_flags?: string[];
}


export type SkillStatus = "draft" | "published";


/** Library card payload. */
export interface SkillSummary {
  skill_id: string;
  title: string;
  summary: string;
  status: SkillStatus;
  step_count: number;
  rule_count: number;
  created_at: string;
  source_video_id?: string | null;
  provenance?: Provenance;
  reviewed?: boolean;
  last_attempt_id?: string | null;
  last_verdict?: Verdict | null;
}


export interface SkillUpdate {
  title?: string | null;
  summary?: string | null;
  objects?: string[] | null;
  steps?: Step[] | null;
  rules?: OrderingRule[] | null;
  confirmed_rule_ids?: string[] | null;
  reviewer_note?: string | null;
  mark_reviewed?: boolean;
}


export interface Step {
  step_id: string;
  title: string;
  action?: string;
  objects?: string[];
  description?: string;
  /** What must be visible for this step to count as done */
  checkpoint?: string;
  common_mistakes?: string[];
  required?: boolean;
  depends_on?: string[];
  evidence?: EvidenceRef[];
  proposed_by_model?: boolean;
}


export type StepState = "pending" | "in_progress" | "done" | "skipped" | "violation" | "uncertain";


export interface TeachRequest {
  video_id: string;
  task_hint?: string;
}


export interface ValidationIssue {
  code: string;
  message: string;
  step_id?: string | null;
  rule_id?: string | null;
}


export interface ValidationResult {
  ok: boolean;
  issues?: ValidationIssue[];
}


export type Verdict = "VERIFIED" | "NOT_VERIFIED" | "INCONCLUSIVE";


/** A stored upload plus what frame extraction found in it. */
export interface VideoMeta {
  video_id: string;
  filename: string;
  content_type: string;
  size_bytes: number;
  duration_s: number;
  fps_source: number;
  width: number;
  height: number;
  sha256: string;
  path: string;
  frames?: Frame[];
  created_at?: string;
  sample_fps?: number;
  /** Scenario id recorded for a bundled sample video, used only to key the offline mock provider. */
  scenario_hint?: string | null;
}


/** What a provider reports seeing in one expert window. Nothing here is a judgement about correctness. The limitations field is where a provider says what it could not see. */
export interface WindowDescription {
  window_id: string;
  t_start: number;
  t_end: number;
  objects?: string[];
  actions?: string[];
  changes?: string[];
  candidate_steps?: string[];
  limitations?: string[];
  evidence: EvidenceRef;
  provenance?: Provenance;
}
