"""Generate the frontend's TypeScript types from the backend Pydantic models.

The API contract lives in `backend/app/domain/models.py`. This script emits the
same shapes as TypeScript so the two sides cannot drift silently: the test
`backend/tests/test_contract.py` regenerates the file and fails when it differs
from what is checked in.

    python scripts/gen_types.py           # write frontend/src/types/api.ts
    python scripts/gen_types.py --check   # exit 1 if the file is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from pydantic import BaseModel  # noqa: E402

from app.api.runs import AttemptDetail, ReplayResponse  # noqa: E402
from app.api.skills import (  # noqa: E402
    AttemptRequest,
    JobAccepted,
    PublishResponse,
    SkillUpdate,
    TeachRequest,
)
from app.domain import models  # noqa: E402

TARGET = REPO_ROOT / "frontend" / "src" / "types" / "api.ts"

ROOTS: list[type[BaseModel]] = [
    models.HealthResponse,
    models.VideoMeta,
    models.SkillGraph,
    models.SkillSummary,
    models.Attempt,
    models.ValidationResult,
    models.ErrorResponse,
    models.EngineResult,
    models.WindowDescription,
    TeachRequest,
    JobAccepted,
    SkillUpdate,
    PublishResponse,
    AttemptRequest,
    AttemptDetail,
    ReplayResponse,
]

HEADER = """/**
 * Generated by scripts/gen_types.py from the backend Pydantic models.
 * Do not edit by hand: run `python scripts/gen_types.py` after changing
 * backend/app/domain/models.py. `pytest backend/tests/test_contract.py`
 * fails when this file is out of date.
 */

"""


def ts_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def convert(schema: dict, defs: dict) -> str:
    if "$ref" in schema:
        return ts_name(schema["$ref"])
    if "anyOf" in schema:
        parts = [convert(option, defs) for option in schema["anyOf"]]
        unique: list[str] = []
        for part in parts:
            if part not in unique:
                unique.append(part)
        return " | ".join(unique)
    if "const" in schema:
        return f'"{schema["const"]}"'
    if "enum" in schema and schema.get("type") == "string":
        return " | ".join(f'"{value}"' for value in schema["enum"])

    kind = schema.get("type")
    if kind == "array":
        item = schema.get("items")
        return f"{convert(item, defs)}[]" if item else "unknown[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {convert(extra, defs)}>"
        return "Record<string, unknown>"
    if kind == "string":
        return "string"
    if kind in ("number", "integer"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    return "unknown"


def emit_definition(name: str, schema: dict, defs: dict) -> str:
    if "enum" in schema:
        values = " | ".join(f'"{value}"' for value in schema["enum"])
        doc = schema.get("description", "")
        prefix = f"/** {doc} */\n" if doc else ""
        return f"{prefix}export type {name} = {values};\n"

    lines: list[str] = []
    doc = schema.get("description", "")
    if doc:
        lines.append(f"/** {' '.join(doc.split())} */")
    lines.append(f"export interface {name} {{")
    required = set(schema.get("required", []))
    for field, field_schema in (schema.get("properties") or {}).items():
        field_doc = field_schema.get("description")
        if field_doc:
            lines.append(f"  /** {' '.join(field_doc.split())} */")
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {convert(field_schema, defs)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render() -> str:
    collected: dict[str, dict] = {}
    order: list[str] = []
    for model in ROOTS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        defs = schema.pop("$defs", {})
        for name, definition in defs.items():
            if name not in collected:
                collected[name] = definition
                order.append(name)
        name = schema.get("title") or model.__name__
        if name not in collected:
            collected[name] = schema
            order.append(name)

    chunks = [HEADER]
    for name in sorted(order):
        chunks.append(emit_definition(name, collected[name], collected))
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    content = render()
    if args.check:
        if not TARGET.exists():
            print(f"{TARGET} is missing. Run: python scripts/gen_types.py")
            return 1
        current = TARGET.read_text(encoding="utf-8")
        if current != content:
            print(
                f"{TARGET} is out of date with the backend models. "
                "Run: python scripts/gen_types.py"
            )
            return 1
        print("Frontend types match the backend models.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
